# Generated by Django 5.2.11 on 2026-03-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('queued', 'Queued'), ('superseded', 'Superseded')], default='pending', max_length=20),
        ),
    ]
