# Generated by Django 5.2.11 on 2026-03-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_deploy_path'),
        ('deployment', '0002_alter_deployment_status'),
        ('services', '0002_allowedcommands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='service',
        ),
        migrations.AddField(
            model_name='deployment',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_deployments', to='deployment.deployment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
