# Generated by Django 5.2.11 on 2026-03-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deploy_path',
            field=models.CharField(default='/opt/dockcd/apps', max_length=255),
        ),
    ]
