# Generated by Django 5.2.11 on 2026-04-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_deploy_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deployment_type',
            field=models.CharField(choices=[(1, 'Podman')], default='docker', max_length=50),
        ),
    ]
