services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: dockcd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
