# Generated by Django 5.2.11 on 2026-03-02 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('compose_file_path', models.CharField(help_text='Relative path to docker-compose file inside repo', max_length=255)),
                ('deploy_path', models.CharField(help_text='Absolute path on this server where repo is cloned', max_length=255)),
                ('auto_deploy', models.BooleanField(default=True, help_text='Deploy automatically on GitHub webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='applications.application')),
            ],
            options={
                'unique_together': {('application', 'name')},
            },
        ),
    ]
