# Generated by Django 5.2.11 on 2026-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_allowedcommands'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deploy_order',
            field=models.IntegerField(default=0),
        ),
    ]
