# Generated by Django 5.2.11 on 2026-04-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_deploy_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='env_file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
