# Generated by Django 5.2.11 on 2026-04-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_env_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desired_commit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_deployed_commit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
