from django.urls import path
from services.views import (
    AllowedCommandListCreateView,
    ContainerLogsView,
    RestartServiceView,
    ServiceContainersView,
    ServiceDeploymentOrderListView,
    ServiceListView,
    ServiceStatusView,
    StartServiceView,
    StopServiceView,
    SyncServiceVIew,
)

urlpatterns = [
    path(
        "allowed-commands/",
        AllowedCommandListCreateView.as_view(),
        name="allowed-command-create"
    ),
    path(
        "",
        ServiceListView.as_view(),
        name="service-list"
    ),
    path(
        "deployment-order/",
        ServiceDeploymentOrderListView.as_view(),
        name="service-deployment-order-list"
    ),
    
    path(
        "<uuid:service_id>/status/",
        ServiceStatusView.as_view(),
        name="service-status"
    ),
    path(
        "<uuid:service_id>/restart/",
        RestartServiceView.as_view(),
        name="service-restart"
    ),
    path(
        "<uuid:service_id>/stop/",
        StopServiceView.as_view(),
        name="service-stop"
    ),
    path(
        "<uuid:service_id>/start/",
        StartServiceView.as_view(),
        name="service-start"
    ),
    path(
        "<uuid:service_id>/containers/",
        ServiceContainersView.as_view(),
        name="service-containers"
    ),
    path(
        "containers/<str:container_name>/logs/",
        ContainerLogsView.as_view(),
        name="container-logs"
    ),
    path(
    "<uuid:service_id>/sync/",
    SyncServiceVIew.as_view(),
)
]
