# Generated by Django 5.2.11 on 2026-04-05 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('applications', '0002_application_deploy_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertrule',
            old_name='frequenecy_minutes',
            new_name='frequency_minutes',
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='application',
            field=models.ForeignKey(default='33c9c778-f8a2-4a9c-b8c4-3d41dd5793d8', on_delete=django.db.models.deletion.CASCADE, related_name='alert_channels', to='applications.application'),
            preserve_default=False,
        ),
    ]
